apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.prc.com
spec:
  group: prc.com
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  defaultCompositeDeletePolicy: Foreground
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              prefix:
                type: string
                description: "(immutable) The prefix to use for the bucket name"
                x-kubernetes-validations:
                - rule: self == oldSelf
              mapstr:
                type: object
                additionalProperties:
                  type: string
                x-kubernetes-map-type: atomic
              mapobj:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    objprop1:
                      type: string
                    objprop2:
                      type: string
                x-kubernetes-map-type: atomic
              strobj:
                type: object
                properties:
                  prop1:
                    type: string
                  prop2:
                    type: string
              arrstr:
                type: array
                items:
                  type: string
              arrobj:
                type: array
                items:
                  type: object
                  properties:
                    arrprop1:
                      type: string
                    arrprop2:
                      type: string
            required:
              - prefix
          status:
            type: object
            properties:
              arn:
                type: string
                description: "ARN of the bucket"