apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buckets.prc.com
spec:
  group: prc.com
  names:
    plural: buckets
    singular: bucket
    kind: Bucket
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                prefix:
                  type: string