name: run-tests
run-name: ${{ github.actor }} is running tests
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Compile and install tfpgen
        run: make install
      - name: Generate and install provider
        working-directory: ./tests/terraform-provider-crd
        run: |
          go mod init github.com/vvbogdanov87/terraform-provider-crd
          tfpgen
          go mod tidy
          go install
          cp .terraformrc /home/runner/.terraformrc
      - uses: azure/setup-helm@v4.2.0
      - uses: kyverno/action-install-chainsaw@v0.1.0
      - uses: helm/kind-action@v1
      - name: Run tests
        working-directory: ./tests
        run: chainsaw test